# Intro to Pandas

In [1]:
import pandas as pd

In [2]:
# Create panda series 
# Series is strictly one dimentional 
data = [1,2,3,4,5,6]
series = pd.Series(data)
series

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
data = [1,2,3,4,5,6]
series = pd.Series(data,index=["idx","idx","idx3","cidx","idx5","idx6"])
series

idx     1
idx     2
idx3    3
cidx    4
idx5    5
idx6    6
dtype: int64

# Pandas Dataframe

In [6]:
# Create pandas dataframe from csv 
test_df = pd.read_csv("test.csv")
test_df.head(5)

  Name   Age
0     A    15
1     B    15
2     C    15
3     D    15
4     E    15

In [8]:
print(test_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    9 non-null      object
 1   Age     9 non-null      int64
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes
None

In [9]:
test_df.describe()

       Age
count   9.0
mean   15.0
std     0.0
min    15.0
25%    15.0
50%    15.0
75%    15.0
max    15.0